---
apiVersion: v1
kind: Job
metadata:
  name: flush-redis
spec:
  template:
  backoffLimit: 1
    spec:
      restartPolicy: Never
      containers:
      - name: flush-redis
        image: quay.io/tparikh/flush-redis:v0.1
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-config
              key: hostname
        - name: REDIS_AUTH
          valueFrom:
            secretKeyRef:
              name: redis-config
              key: auth
