---
apiVersion: v1
kind: Template
metadata:
  name: flush-redis
parameters:
- name: REDIS_SECRET
  value: ""
  required: true
- name: IMAGE
  value: "quay.io/tparikh/flush-redis"
  required: true
- name: IMAGE_TAG
  value: ""
  required: true
- name: ACTIVE_DEADLINE_SECONDS
  value: "600"
  required: true
- name: JOB_NAME
  value: ""
  required: true
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: flush-redis-${JOB_NAME}
  spec:
    template:
      metadata:
        labels:
          app: flush-redis-${JOB_NAME}
      spec:
        activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
        backoffLimit: 1
        completions: 1
        parallelism: 1
        restartPolicy: Never
        containers:
        - name: flush-redis-${JOB_NAME}
          image: ${IMAGE}:${IMAGE_TAG}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: ${{REDIS_SECRET}}
                key: hostname
          - name: REDIS_AUTH
            valueFrom:
              secretKeyRef:
                name: ${{REDIS_SECRET}}
                key: auth
